name: Test

on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Install e2e dependencies
        run: sudo apt-get install -y dnsutils

      - name: Allow unprivileged user namespaces
        run: sudo sysctl -w kernel.unprivileged_userns_clone=1 || true

      - name: Test
        run: make test
